# Generated by Django 4.2.1 on 2023-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_category_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Author name')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='cat_author', to='main.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
