# Generated by Django 4.2.1 on 2023-05-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Author name'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Author name'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Author name'),
        ),
        migrations.AddField(
            model_name='book',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Book about'),
        ),
        migrations.AddField(
            model_name='book',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Book about'),
        ),
        migrations.AddField(
            model_name='book',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Book about'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Book name'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Book name'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Book name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
    ]
