# Generated by Django 4.2.1 on 2023-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_author_name_en_author_name_hy_author_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('review', models.TextField(verbose_name='Contact review')),
            ],
        ),
    ]
